# Generated by Django 5.0.2 on 2024-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('board', models.CharField(default='---------', max_length=9)),
                ('player1', models.CharField(default='', max_length=255)),
                ('player2', models.CharField(default='', max_length=255)),
                ('turn', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=0)),
            ],
        ),
    ]
