# Generated by Django 5.0.2 on 2024-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
